name: reusable_pytest_workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Stringified JSON object listing target Python versions'
        required: true
        type: string

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python_version) }}


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install .[examples]
    - name: Test with pytest
      run: |
        pytest $GITHUB_WORKSPACE/tests/test.py
