name: integration_tests

on:
  push:
  pull_request:

jobs:

  run-pytest:
    # FIXME: This part will have to be updated whenever github allows
    # for dynamic name resolution at both repo (Rodrigo-Tenorio/distromax)
    # and refenrec (master) level.
    uses: Rodrigo-Tenorio/distromax/.github/workflows/run-pytest.yml@master
    with:
      python_version: "[\"3.8\", \"3.9\"]"
